import { useSession } from 'next-auth/react';
import Head from 'next/head';
import { GetServerSidePropsContext, GetServerSidePropsResult } from 'next';
import { db } from '@/lib/firestore';
import { collection, getDocs } from 'firebase/firestore';
import Image from 'next/image';

type Users = {
	email: string;
	emailverified: unknown;
	image: string;
	name: string;
};
export default function Home({ data }: { data: Users[] }) {
	const { data: session } = useSession();

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main>
				<Image width={50} height={50} alt='' src={data[0].image} />
				{session?.user.name}
			</main>
		</>
	);
}

type Context = GetServerSidePropsContext;
type Result = GetServerSidePropsResult<{ data: Users[] }>;

export async function getServerSideProps(ctx: Context): Promise<Result> {
	const users = await getDocs(collection(db, 'users'));
	const data = users.docs.map((user) => user.data()) as Users[];

	return {
		props: {
			data,
		},
	};
}
